### ISSUE TITLE
Issue while running the LISFLOOD test case in LINUX

### ISSUE THREAD

**Issue by diksha922** [ec-jrc/lisflood-code#125]
Sir/ Madam,

I am facing the parse string error while running the test case.

(lisflood) diksha@diksha-VirtualBox:~/lisflood-code$ python src/lisf1.py /home/diksha/lisflood-usecases-master/LF_lat_lon_UseCase/settings_lat_lon-Run.xml
Traceback (most recent call last):
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 614, in calendar
    return float(date_in)
ValueError: could not convert string to float: '02/01/1986 00:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 619, in calendar
    date = parsing.parse_time_string(date_in, dayfirst=True)[0]  # datetime.datetime type
AttributeError: module 'pandas._libs.tslibs.parsing' has no attribute 'parse_time_string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/lisf1.py", line 34, in <module>
    sys.exit(main())
  File "/home/diksha/lisflood-code/src/lisflood/main.py", line 218, in main
    lissettings = LisSettings(settings_file, sys_args)
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 111, in __call__
    cls._instances[key] = super(ThreadSingleton, cls).__call__(*args, **kwargs)
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 290, in __init__
    self.model_steps = self._model_steps()
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 370, in _model_steps
    int_start, int_end = self._check_simulation_dates()
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 352, in _check_simulation_dates
    begin = calendar(self.binding['CalendarDayStart'], self.binding['calendar_type'])
  File "/home/diksha/lisflood-code/src/lisflood/global_modules/settings.py", line 625, in calendar
    raise LisfloodError(msg)
lisflood.global_modules.errors.LisfloodError: 

 ========================== LISFLOOD ERROR =============================
Wrong step or date format in XML settings file
 Input 02/01/1986 00:00

Please resolve the issue.

**Comment by doc78** [comment]
Hi [diksha922](https://github.com/diksha922)

Can you please provide further info on this error (lisflood version and XML files you are using)? Using the new version of lisflood and the current update master branch of lisflood-usecase you shouldn't have any issue.

I just ran the following steps without any issue:

python lisflood-code/src/lisf1.py lisflood-usecases/LF_lat_lon_UseCase/settings_lat_lon-PreRun.xml
python lisflood-code/src/lisf1.py lisflood-usecases/LF_lat_lon_UseCase/settings_lat_lon-Run.xml

(you will need to execute the PreRun first, then the Run xml file).

Please let me know

Cheers
Carlo
