### ISSUE TITLE
How to install lisflood in conda environment

### ISSUE THREAD

**Issue by li6364** [ec-jrc/lisflood-code#149]
After I installed the conda environment, I installed lisflood using the conda virtual environment according to the installation steps in the guide, but it keeps showing the error: metadata-generation-failed.
I have tried multiple methods. Including downloading the source code of lisflood to install it also shows the same error. Installing lisflood-utilities first also shows the error and I can't find a solution anymore.
Can you please tell me if there is any solution?

Translated with www.DeepL.com/Translator (free version)

**Comment by li6364** [comment]
My OS is Win10, but I have tried on both Windows & linux.
After running it will show：
Collecting lisflood-model
  Using cached lisflood-model-4.3.1.tar.gz (168 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jndx1\AppData\Local\Temp\pip-install-n_04f7l3\lisflood-model_9809468fa8074592b51ddd7913d6ef26\setup.py", line 124, in _get_gdal_version
          p = subprocess.Popen(['gdal-config', '--version'], stdout=subprocess.PIPE)
        File "C:\Users\jndx1\.conda\envs\lisflood1\lib\subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "C:\Users\jndx1\.conda\envs\lisflood1\lib\subprocess.py", line 1207, in _execute_child
          startupinfo)
      FileNotFoundError: [WinError 2] The system cannot find the specified file.
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jndx1\AppData\Local\Temp\pip-install-n_04f7l3\lisflood-model_9809468fa8074592b51ddd7913d6ef26\setup.py", line 134, in <module>
          gdal_version = _get_gdal_version()
        File "C:\Users\jndx1\AppData\Local\Temp\pip-install-n_04f7l3\lisflood-model_9809468fa8074592b51ddd7913d6ef26\setup.py", line 126, in _get_gdal_version
          raise SystemError('gdal-config not found.'
      SystemError: gdal-config not found.GDAL seems not installed. Please, install GDAL binaries and libraries for your system and then install the relative pip package.
      >>>>>>>>>>>>>>>> Building LISFLOOD version 4.3.1 <<<<<<<<<<<<<<<<<<
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by doc78** [comment]
Unfortunately we do not provide support for Windows OS.
Can you please send the Linux version and related logs?

**Comment by doc78** [comment]
The full installation should be done on a Linux operating system. Thus you need to create the conda env in a Linux OS.

**Comment by li6364** [comment]
ok，thanks

**Comment by li6364** [comment]
I try it again
