### ISSUE TITLE
Reservoir Output Data Not Generated

### ISSUE THREAD

**Issue by Nooshdokht-Bayatafshary** [ec-jrc/lisflood-code#171]
Dear @StefaniaGrimaldi,

I am currently running LISFLOOD for a basin that contains one reservoir. In my configuration, I have specified the necessary keys in the XML file ([Settings.zip](https://github.com/user-attachments/files/17004995/Settings.zip)) to export reservoir outputs such as inflow and outflow. However, these outputs are not being generated as expected.

```
<setoption choice="1" name="simulateReservoirs"/>
<setoption choice="1" name="repsimulateReservoirs"/>
```

I’ve double-checked the XML setup, but I’m unsure what might be causing this issue. I’ve attached my setup data for the basin for further inspection [(data).](https://drive.google.com/file/d/14yDY3_QVQOzjIoDQ83gR6m4dOdLIhNym/view?usp=drive_link)

Could you please advise on what might be going wrong or if there are any additional steps required to enable reservoir output generation?

Thank you for your time and assistance!

Best regards,
Nooshdokht

**Comment by StefaniaGrimaldi** [comment]
Dear @Nooshdokht-Bayatafshary,

thank you for your enquiry.

The option "repsimulateReservoirs" allows to print the time series (.tss format) of the level of filling, inflow, and outflow for each reservoir included in the computational domain (
 https://github.com/ec-jrc/lisflood-code/blob/fe94c33b6bd9fe09fa7be43a6dd4fdc8a11f744c/src/lisflood/global_modules/default_options.py#L1363, https://github.com/ec-jrc/lisflood-code/blob/fe94c33b6bd9fe09fa7be43a6dd4fdc8a11f744c/src/lisflood/global_modules/default_options.py#L1367, https://github.com/ec-jrc/lisflood-code/blob/fe94c33b6bd9fe09fa7be43a6dd4fdc8a11f744c/src/lisflood/global_modules/default_options.py#L1371).

In the xml file "settings_calibration_daily2001Runlong_term_run.xml", "repsimulateReservoirs"  is set to 1 in line 72, but then to 0 in line 87 (this latter setting switches off the printing function). Could you please confirm that I am looking at the correct xml file?

In case you wished to print netcdf gridded outputs of the level of filling of reservoirs, you would need to activate "repStateMaps". Inflow and outflows in netcdf gridded format can be extracted from dis.nc ("repDischargeMaps").

I hope that this answer helps,
kind regards,
Stefania

**Comment by Nooshdokht-Bayatafshary** [comment]
Dear @StefaniaGrimaldi,

Thank you for your detailed response. You were absolutely right—the issue was caused by the conflicting setting in the XML file. I removed the second occurrence of _repsimulateReservoirs_ in line 87, as you suggested. However, I am now encountering a new error:
```
Traceback (most recent call last):
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/bin/lisflood", line 41, in <module>
    sys.exit(main())
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/lib/python3.8/site-packages/lisflood/main.py", line 226, in main
    lisfloodexe(lissettings)
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/lib/python3.8/site-packages/lisflood/main.py", line 90, in lisfloodexe
    Lisflood = LisfloodModel()
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/lib/python3.8/site-packages/lisflood/Lisflood_initial.py", line 236, in __init__
    self.output_module.initial()
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/lib/python3.8/site-packages/lisflood/global_modules/output.py", line 535, in initial
    self.var.Tss[tss] = TimeoutputTimeseries(str(binding[tss]), self.var, outpoints, noHeader=flags['noheader'])
  File "/home/n.bayatafshary74.student.sharif/.conda/envs/lis3.8/lib/python3.8/site-packages/lisflood/global_modules/zusatz.py", line 374, in __init__
    outlet_idx = np.where(codesId == outlet_code)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
It seems to be related to the _ReservoirFillTS_ key based on the output when I printed binding[tss]. I'm not quite sure what’s causing the problem. Could you kindly help me troubleshoot this?

Thanks again for your assistance!

Best regards,
Nooshdokht

**Comment by StefaniaGrimaldi** [comment]
Dear @Nooshdokht-Bayatafshary,

I am sorry for the delay. @doc78 and I finally found some time to explore your issue.

The problem is a consequence of missing metadata in your input netcdf maps (e.g. res.nc).

Specifically, the function that writes .tss files crashes because missing_value is not set. This explains the error when you activate _repsimulateReservoirs_.
Furthermore, output files in netcdf format are regularly written but they do not have any reference system.

To solve the issue, you need to set the metadata in your input maps, particularly important are 
missing_value, _FillValue, and reference system.

We hope that this message helps,
we are at your disposal for further discussions,
kind regards,
Carlo and Stefania

**Comment by Nooshdokht-Bayatafshary** [comment]
Dear @StefaniaGrimaldi and @doc78,

I hope this message finds you well.

First, I’d like to thank you again for your previous support. I recently revisited your response from October regarding the `res.nc` file and missing metadata, but unfortunately, I had missed the notification and only saw your reply recently — I sincerely apologize for the delayed follow-up.

I’ve now implemented your suggestions and created a new `res.nc` file with the necessary metadata (including `_FillValue`, projection, etc.). The file structure now matches the example on the LISFLOOD GitHub repository. However, after rerunning the model, I’m still unable to generate the `.tss` reservoir output files, even though `simulateReservoirs` and `repsimulateReservoirs` are correctly set in the XML file.

Additionally, I’ve encountered another issue. I tried enabling other time series and map outputs in the XML ([XML.zip](https://github.com/user-attachments/files/20639264/XML.zip)) (e.g., `repTotalWUse`, `repTotalAbs`, `repWaterLevelTs`). Some of these outputs are generated successfully, but others are not (e.g.,  `AreatotalIrrigationUseM3`, `WaterLevelMaps`, `UZTS`, `UZAvUpsTS`, `IrrigationWaterAbstraction` etc. ) —despite being documented in the LISFLOOD [user manual](https://ec-jrc.github.io/lisflood-code/4_annex_settings_and_options/). I checked the source code (particularly `default_options.py`) and noticed that not all keys listed in the manual are included in the actual source code. This has left me uncertain:

- Are all documented keys in the manual still supported?
- If not, is it safe (or sufficient) to manually add the missing keys to default_options.py? Or is further implementation required elsewhere in the LISFLOOD codebase?

To give you more context: I am working on a detailed hydrological analysis of my study basin, which includes one dam and multiple sources of water abstraction such as reservoirs, surface water, and groundwater withdrawals used for irrigation and domestic water demands. I am currently analyzing the model calibration results, and I need to extract various time series to understand the system’s behavior and identify why calibration performance is unsatisfactory. In particular, I would like to extract the groundwater level relative to the surface elevation across the basin. Could you please advise me on which key or configuration is appropriate for obtaining this variable, if available in LISFLOOD?

Your guidance would be greatly appreciated. Please let me know if I can share any example files to support debugging.

Warm regards,
Nooshdokht

**Comment by fuchsiger** [comment]
Dear Nooshdokht,

apologise the delayed answer, however, I think we can close this ticket with a short summary on the last part of the open question: 
Please note that LISFLOOD has not a groundwater level or water-table depth variable due to it's conceptual groundwater representation (it is not a physically-based groundwater model). We just offer conceptually the UZ and LZ stores of course, however, they are not equivalent to a groundwater level relative to the surface. 

Best regards,

Timo
