### ISSUE TITLE
Fix for usecases

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-code#27]
Use case `LF_ETRS89_UseCase`  has input files that raise this exception in lisflood:

```console
Traceback (most recent call last):
  File "/workarea/virtualenvs/lisflood27/bin/lisflood", line 41, in <module>
    sys.exit(main())
  File "/workarea/virtualenvs/lisflood27/lib/python2.7/site-packages/lisflood/main.py", line 224, in main
    Lisfloodexe(settings, optionxml)
  File "/workarea/virtualenvs/lisflood27/lib/python2.7/site-packages/lisflood/main.py", line 78, in Lisfloodexe
    Lisflood = LisfloodModel()
  File "/workarea/virtualenvs/lisflood27/lib/python2.7/site-packages/lisflood/Lisflood_initial.py", line 118, in __init__
    self.misc_module.initial()
  File "/workarea/virtualenvs/lisflood27/lib/python2.7/site-packages/lisflood/hydrological_modules/miscInitial.py", line 181, in initial
    raise Exception("If using projected coordinates (x, y), a variable with the 'proj4_params' attribute must be included in the precipitation file!")
Exception: If using projected coordinates (x, y), a variable with the 'proj4_params' attribute must be included in the precipitation file!

```

Trying to solve/mitigate by giving the option to the user to insert a proj4 definition into settings file.

**Comment by domeniconappo** [comment]
Linked/same of
https://github.com/ec-jrc/lisflood-usecases/issues/4
