### ISSUE TITLE
"gdal-config not found.GDAL seems not installed. Please, install GDAL binaries and libraries for your system " Error at windows 

### ISSUE THREAD

**Issue by aefeakn** [ec-jrc/lisflood-code#92]
I took the following error while trying to install lisflood. This is on miniconda terminal :
```
Traceback (most recent call last):
        File "C:\Users\ahmet\AppData\Local\Temp\pip-install-e4eqej85\lisflood-model_7d34769dd15e4caa82bb4befdfd11a26\setup.py", line 145, in _get_gdal_version
          p = subprocess.Popen(['gdal-config', '--version'], stdout=subprocess.PIPE)
        File "C:\Users\ahmet\miniconda3\envs\lisflood\lib\subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "C:\Users\ahmet\miniconda3\envs\lisflood\lib\subprocess.py", line 1207, in _execute_child
          startupinfo)
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ahmet\AppData\Local\Temp\pip-install-e4eqej85\lisflood-model_7d34769dd15e4caa82bb4befdfd11a26\setup.py", line 155, in <module>
          gdal_version = _get_gdal_version()
        File "C:\Users\ahmet\AppData\Local\Temp\pip-install-e4eqej85\lisflood-model_7d34769dd15e4caa82bb4befdfd11a26\setup.py", line 147, in _get_gdal_version
          raise SystemError('gdal-config not found.'
      SystemError: gdal-config not found.GDAL seems not installed. Please, install GDAL binaries and libraries for your system and then install the relative pip package.
      >>>>>>>>>>>>>>>> Building LISFLOOD version 3.1.1 <<<<<<<<<<<<<<<<<<
      [end of output]
```
I tried to install gdal like this : 
```
conda create -n gdal_test python=3.5
activate gdal_test
conda install gdal
```
but did not give any results...

**Comment by aefeakn** [comment]
I ended up creating a Linux Box and then install Lisflood in it just as it is told in here. [https://github.com/ec-jrc/lisflood-code/issues/91](url) Good luck everyone.
